'use client'

import React, { useState, ChangeEvent } from "react";

type Option = [string, string[]];

const Difficulty = ({setList}:any): JSX.Element => {
  /*const [selectedElements, setSelectedElements] = useState<string[]>([]);
  const [selectedOption, setSelectedOption] = useState<string>("");*/

  const optionsList: Option[] = [
    ["Easy", [
        "The sun is shining brightly today.",
        "I love going for long walks in the park.",
        "Her smile brightened up the room.",
        "The cat chased the mouse around the house.",
        "I enjoy reading books in my free time.",
        "He played the guitar at the concert last night.",
        "The mountains are covered in snow.",
        "I can't wait to see you again.",
        "She wrote a heartfelt letter to her best friend.",
        "The car broke down on the highway.",
        "I'm feeling tired after a long day at work.",
        "The children played happily in the playground.",
        "The flowers bloomed beautifully in the spring.",
        "He scored a goal in the final minute of the game.",
        "I'm going on vacation next week.",
        "She cooked a delicious meal for her family.",
        "The train arrived at the station on time.",
        "I need to buy groceries for the week.",
        "They went swimming in the ocean.",
        "I enjoy listening to music while I work.",
        "The movie was entertaining and funny.",
        "I'm learning a new language.",
        "The rain stopped and a rainbow appeared in the sky.",
        "She wore a stunning red dress to the party.",
        "I'm excited about the upcoming concert.",
        "He built a sandcastle at the beach.",
        "The dog wagged its tail happily.",
        "I like to drink coffee in the morning.",
        "She received a promotion at work.",
        "The book kept me captivated until the last page.",
        "I'm planning a surprise party for my friend.",
        "He ran a marathon and finished in first place.",
        "The painting hung on the wall of the museum.",
        "I enjoy spending time with my family and friends.",
        "She won an award for her outstanding performance.",
        "The alarm clock woke me up early in the morning.",
        "I'm going to the gym to exercise.",
        "He played the piano beautifully.",
        "The birds chirped merrily in the trees.",
        "I'm studying for an important exam.",
        "She baked a delicious cake for her sister's birthday.",
        "The soccer team won the championship.",
        "I'm looking forward to the weekend.",
        "He wrote a heartfelt poem for his girlfriend.",
        "The river flowed peacefully through the valley.",
        "I enjoy watching movies at the cinema.",
        "She gave a speech at the conference.",
        "The snowflakes fell gently from the sky.",
        "I'm going to the beach to relax.",
        "He helped his neighbor carry groceries.",
        "The museum displayed ancient artifacts.",
        "I'm taking a photography class.",
        "She danced gracefully on the stage.",
        "The wind blew through the trees.",
        "I'm volunteering at a local charity.",
        "He fixed the broken bicycle.",
        "The fireworks lit up the night sky.",
        "I enjoy cooking dinner for my family.",
        "She sang a beautiful song at the talent show.",
        "The waves crashed against the shore.",
        "I'm going to a concert with my friends.",
        "He wrote a book about his travels.",
        "The stars twinkled in the dark night.",
        "I'm starting a new job next month.",
        "She planted flowers in her garden.",
        "The basketball team won the game.",
        "I'm going to a party this weekend.",
        "He painted a colorful mural on the wall.",
        "The leaves rustled in the autumn breeze.",
        "I'm attending a wedding next week.",
        "She adopted a stray kitten.",
        "The orchestra played a beautiful symphony.",
        "I'm going on a road trip with my family.",
        "He took a photograph of the sunset.",
        "The city skyline was breathtaking.",
        "I'm learning how to play the guitar.",
        "She ran a marathon and crossed the finish line.",
        "The thunderstorm raged outside.",
        "I'm going to a music festival this summer.",
        "He cooked a delicious meal for his friends.",
        "The sun set behind the mountains.",
        "I'm going to the theater to watch a play.",
        "She donated money to a local charity.",
        "The flowers bloomed in vibrant colors.",
        "I'm attending a conference next month.",
        "He built a birdhouse in his backyard.",
        "The children laughed and played together.",
        "I'm going to a museum to see an art exhibit.",
        "She learned how to swim.",
        "The waterfall cascaded down the rocks.",
        "I'm starting a new project at work.",
        "He baked cookies for his coworkers.",
        "The autumn leaves fell from the trees.",
        "I'm going on a hiking trip next weekend.",
        "She painted a portrait of her family.",
        "The waves crashed against the cliff.",
        "I'm going to a comedy show tonight.",
        "He volunteered at a homeless shelter.",
        "The sunflower turned towards the sun.",
        "I'm taking a yoga class to relax.",
        "She won a scholarship to study abroad.",
        "The symphony orchestra performed a beautiful concert.",
        "I'm going to a baseball game with my friends.",
        "He wrote a screenplay for a movie.",
        "The snow covered the ground in a thick blanket.",
        "I'm going to a fancy restaurant for dinner.",
        "She danced in the rain and didn't care.",
        "The windmill spun in the breeze.",
        "I'm starting a new hobby.",
        "He taught his son how to ride a bike.",
        "The fireworks lit up the sky in brilliant colors.",
        "I'm going to a music concert this weekend."
      ]
    ],["Medium", [
        "Le soleil brille intensément aujourd'hui.",
        "J'adore faire de longues promenades dans le parc.",
        "Son sourire illumina la pièce.",
        "Le chat poursuivait la souris dans toute la maison.",
        "J'aime lire des livres pendant mon temps libre.",
        "Il a joué de la guitare au concert hier soir.",
        "Les montagnes sont recouvertes de neige.",
        "Je suis impatient de te revoir.",
        "Elle a écrit une lettre sincère à sa meilleure amie.",
        "La voiture est tombée en panne sur l'autoroute.",
        "Je suis fatigué après une longue journée de travail.",
        "Les enfants jouaient joyeusement dans l'aire de jeux.",
        "Les fleurs ont magnifiquement fleuri au printemps.",
        "Il a marqué un but à la dernière minute du match.",
        "Je pars en vacances la semaine prochaine.",
        "Elle a cuisiné un délicieux repas pour sa famille.",
        "Le train est arrivé à l'heure à la gare.",
        "J'ai besoin d'acheter des courses pour la semaine.",
        "Ils sont allés nager dans l'océan.",
        "J'aime écouter de la musique pendant que je travaille.",
        "Le film était divertissant et drôle.",
        "J'apprends une nouvelle langue.",
        "La pluie s'est arrêtée et un arc-en-ciel est apparu dans le ciel.",
        "Elle portait une superbe robe rouge à la fête.",
        "Je suis excité à l'idée du prochain concert.",
        "Il a construit un château de sable sur la plage.",
        "Le chien remuait joyeusement la queue.",
        "J'aime boire du café le matin.",
        "Elle a reçu une promotion au travail.",
        "Le livre m'a captivé jusqu'à la dernière page.",
        "Je prépare une fête surprise pour mon ami.",
        "Il a couru un marathon et a terminé premier.",
        "Le tableau était accroché au mur du musée.",
        "J'aime passer du temps avec ma famille et mes amis.",
        "Elle a remporté un prix pour sa performance exceptionnelle.",
        "Le réveil m'a réveillé tôt le matin.",
        "Je vais à la salle de sport pour faire de l'exercice.",
        "Il jouait du piano magnifiquement.",
        "Les oiseaux gazouillaient joyeusement dans les arbres.",
        "Je suis en train de réviser pour un examen important.",
        "Elle a fait cuire un délicieux gâteau pour l'anniversaire de sa sœur.",
        "L'équipe de soccer a remporté le championnat.",
        "J'attends avec impatience le week-end.",
        "Il a écrit un poème sincère pour sa petite amie.",
        "La rivière coulait paisiblement à travers la vallée.",
        "J'aime regarder des films au cinéma.",
        "Elle a prononcé un discours lors de la conférence.",
        "Les flocons de neige tombaient doucement du ciel.",
        "Je vais à la plage pour me détendre.",
        "Il a aidé son voisin à porter des courses.",
        "Le musée exposait des artefacts anciens.",
        "Je suis en train de suivre un cours de photographie.",
        "Elle dansait avec grâce sur scène.",
        "Le vent soufflait à travers les arbres.",
        "Je fais du bénévolat dans une association caritative locale.",
        "Il a réparé le vélo cassé.",
        "Les feux d'artifice ont illuminé le ciel nocturne.",
        "J'aime cuisiner le dîner pour ma famille.",
        "Elle a chanté une belle chanson lors du spectacle de talents.",
        "Les vagues se brisaient contre la rive.",
        "Je vais à un concert avec mes amis.",
        "Il a écrit un livre sur ses voyages.",
        "Les étoiles scintillaient dans la nuit sombre.",
        "Je vais commencer un nouvel emploi le mois prochain.",
        "Elle a planté des fleurs dans son jardin.",
        "L'équipe de basket-ball a remporté le match.",
        "Je vais à une fête ce week-end.",
        "Il a peint une fresque colorée sur le mur.",
        "Les feuilles bruissaient dans la brise d'automne.",
        "Je vais assister à un mariage la semaine prochaine.",
        "Elle a adopté un chaton errant.",
        "L'orchestre a joué un magnifique concert symphonique.",
        "Je vais faire un voyage en voiture avec ma famille.",
        "Il a pris une photo du coucher de soleil.",
        "La ligne d'horizon de la ville était à couper le souffle.",
        "J'apprends à jouer de la guitare.",
        "Elle a couru un marathon et a franchi la ligne d'arrivée.",
        "L'orage faisait rage dehors.",
        "Je vais à un festival de musique cet été.",
        "Il a cuisiné un délicieux repas pour ses amis.",
        "Le soleil s'est couché derrière les montagnes.",
        "Je vais au théâtre pour regarder une pièce.",
        "Elle a fait un don à une association caritative locale.",
        "Les fleurs ont fleuri dans des couleurs vives.",
        "Je vais assister à une conférence le mois prochain.",
        "Il a construit une nichoir dans son jardin.",
        "Les enfants riaient et jouaient ensemble.",
        "Je vais au musée pour voir une exposition d'art.",
        "Elle a appris à nager.",
        "La cascade tombait en cascades sur les rochers.",
        "Je vais commencer un nouveau projet au travail.",
        "Il a cuisiné des cookies pour ses collègues.",
        "Les feuilles d'automne tombaient des arbres.",
        "Je vais partir en randonnée le week-end prochain.",
        "Elle a peint un portrait de sa famille.",
        "Les vagues se brisaient contre la falaise.",
        "Je vais à un spectacle comique ce soir.",
        "Il a fait du bénévolat dans un refuge pour sans-abri.",
        "Le tournesol se tournait vers le soleil.",
        "Je suis en train de suivre un cours de yoga pour me détendre.",
        "Elle a remporté une bourse d'études pour étudier à l'étranger.",
        "L'orchestre symphonique a donné un magnifique concert.",
        "Je vais à un match de baseball avec mes amis.",
        "Il a écrit un scénario pour un film.",
        "La neige a recouvert le sol d'une épaisse couverture.",
        "Je vais dans un restaurant chic pour dîner.",
        "Elle dansait sous la pluie et s'en fichait.",
        "Le moulin à vent tournait dans la brise.",
        "Je commence un nouveau passe-temps.",
        "Il a appris à son fils à faire du vélo.",
        "Les feux d'artifice ont illuminé le ciel de couleurs brillantes.",
        "Je vais à un concert de musique ce week-end."
      ]]
  ];
  const [selectedOption, setSelectedOption] = useState<String>(optionsList[0][0]);

  function findValueByIndex(arr:Option[], index:String) {
    for (let i = 0; i < arr.length; i++) {
      if (arr[i][0] === index) {
        return arr[i][1];
      }
    }
    return null; // Return null if index is not found
  }

  const handleOptionChange = (event: ChangeEvent<HTMLSelectElement>): void => {
    setSelectedOption(event.target.value);
    setList(findValueByIndex(optionsList,event.target.value));
  };

  return (
    <div>
      <select value={selectedOption.valueOf()} onChange={handleOptionChange} className="block w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 sm:text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        {optionsList.map((option: Option, index: number) => (
          <option key={index} value={option[0]} className="block w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 sm:text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
            {option[0]}
          </option>
        ))}
      </select>
    </div>
  );
};

export default Difficulty;
